import Head from 'next/head'
import Image from 'next/image'
import { useWallet } from '@solana/wallet-adapter-react'
import ConnectWallet from '../components/connectwallet/connectwallet.js'
import UseWebsite from '../components/UseWebsite.js'

export default function LogToWebsite() {
  const { connected } = useWallet()
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      { connected ? (
        <UseWebsite/>
      ) : (
        <ConnectWallet/>
      ) }
    </div>
  )
}
