[features]
seeds = false
[programs.localnet]
health_care_trace = "DSb71pb4Tfs9F5bkzX69JQFrZoXnUeqBkufndfGk62JX"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
#wallet = "/home/somaya/.config/solana/id.json"
wallet = "/home/ghmaimon/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
